### ISSUE TITLE
Add proper data-cy selectors for file picker

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud-libraries/nextcloud-dialogs#1001]
It would be great to have unique selectors for elements, especially file list entries to pick them during testing

https://docs.cypress.io/guides/references/best-practices

For files we currently only can use the title attribute which doesn't contain the file extension

**Comment by susnux** [comment]
Duplicate of https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/924 (partly implemented https://github.com/nextcloud-libraries/nextcloud-dialogs#test-selectors )
