### ISSUE TITLE
FilePicker component can not be closed by click outside

### ISSUE THREAD

**Issue by Antreesy** [nextcloud-libraries/nextcloud-dialogs#1168]
After merging https://github.com/nextcloud-libraries/nextcloud-vue/pull/5062 and bumping the vue-library:
- prop `closeOnClickOutside` should be passed here (or be `true` by default):
https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/f69b6f18969281e48285a9a8fc984417ec3f3164/lib/components/FilePicker/FilePicker.vue#L123-L134

**Comment by susnux** [comment]
cc @jancborchardt 

I am not sure about the UX here, see also my comment here https://github.com/nextcloud-libraries/nextcloud-vue/pull/5062#issuecomment-1890460961

**Comment by susnux** [comment]
cc @nextcloud-libraries/developers

**Comment by jancborchardt** [comment]
Agree with @susnux’s assessment in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5062#issuecomment-1890460961 – it is too risky and annoying to have changes vanish by accidentally clicking or tapping outside, even if it is just navigating into a sub-sub-subfolder and finally finding the file you were looking for. The X button is there and always there, it doesn’t need a huge "CLOSE" area around the whole dialog too. :)

**Comment by Antreesy** [comment]
Ok, then I'm closing it
