### ISSUE TITLE
Image previews are detached from dialog container

### ISSUE THREAD

**Issue by Antreesy** [nextcloud-libraries/nextcloud-dialogs#1221]
To reproduce:
1. Open Files
2. Try to move/copy something
3. Navigate with FilePicker to the folder with many directories
4. See `<img />` elements appended to `<body />` flowing on the screen

[Screencast from 01.02.2024 18:09:50.webm](https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/93392545/b4030bd8-92d3-4e3b-ae96-2a8bf8a0820d)

Or:
1. Open Talk
2. Try to share something from Nextcloud to conversation
3. Navigate with FilePicker to the folder with many directories  / files
4. See `<img />` elements appended to `<body />` flowing on the screen

[Screencast from 01.02.2024 18:13:04.webm](https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/93392545/bfc7fb26-02b7-4144-9c03-b105f1286d81)

**Comment by Antreesy** [comment]
Could it come from this changes? https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/15c021544d2f62815f3c24d5277ed7086bb605ce/lib/components/FilePicker/FilePreview.vue#L34-L38
cc @susnux

**Comment by susnux** [comment]
It adds the file to body to check if loading works and let the browser cache the image.

**Comment by Antreesy** [comment]
> It should not cause any issues, do you experience any issues?

Yes, same floating previews, as on provided screencasts, happen in 28 production
