### ISSUE TITLE
File Picker doesn't show groupfolders when you're in the root folder

### ISSUE THREAD

**Issue by Chartman123** [nextcloud-libraries/nextcloud-dialogs#1283]
When you're in the root folder inside the File Picker, groupfolders aren't listed:

![image](https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/16020496/e13d41a4-a934-4d2d-aa20-94d9db65720b)

I don't know if this also affects other shared folders as I currently don't have any.

**Comment by susnux** [comment]
> When you're in the root folder inside the File Picker, groupfolders aren't listed:

Can you check that you have write permissions for those files? From which app do you use the file picker?

Because if you are in the files app and try to move a file, there is a known bug for group folders without write permission:
https://github.com/nextcloud/server/issues/44649

**Comment by Chartman123** [comment]
> Because if you are in the files app and try to move a file, there is a known bug for group folders without write permission:
> https://github.com/nextcloud/server/issues/44649

OK, then it seems to be this bug. First level of group folders are RO for all users...

**Comment by susnux** [comment]
Ok then this will be fixed with https://github.com/nextcloud/server/pull/45688
