### ISSUE TITLE
Catalan Translation Typo

### ISSUE THREAD

**Issue by xavi-GH** [nextcloud-libraries/nextcloud-dialogs#1319]
The catalan file translation of dialogs, contains a typo. Within file:
https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/main/l10n/ca.pot

The text:

msgid "Move to {target}"
msgstr "More a {target}"

Shoud be:

msgid "Move to {target}"
msgstr "Moure a {target}"

Note the new "u" character.

**Comment by susnux** [comment]
Thank you for the report.
Translations are managed on Transifex, you can even submit your fix there: https://explore.transifex.com/nextcloud/nextcloud-dialogs-library/
