### ISSUE TITLE
addButton is not a function

### ISSUE THREAD

**Issue by Thatoo** [nextcloud-libraries/nextcloud-dialogs#1353]
```
export function openFilePickerClipboardOnly() {
	const filePicker = getFilePickerBuilder(t('picker', 'Choose a file to share a link to it'))
		.allowDirectories(true)
		.setMultiSelect(false)
		.build()
	filePicker.pick()
}
```
works!

However, if I modify it to

```
export function openFilePickerClipboardOnly() {
	const filePicker = getFilePickerBuilder(t('picker', 'Choose a file to share a link to it'))
		.allowDirectories(true)
		.setMultiSelect(false)
		.addButton({
			label: 'Read Only public share link',
			callback: (nodes) => console.log('Picked', nodes),
			type: 'primary',
		})
		.build()
	filePicker.pick()
}
```

then it's not working and I get the following error in console : 
`Uncaught TypeError: _nextcloud_dialogs__WEBPACK_IMPORTED_MODULE_4__.getFilePickerBuilder(...).allowDirectories(...).setMultiSelect(...).addButton is not a function`

Is this Readme wrong https://github.com/nextcloud-libraries/nextcloud-dialogs?tab=readme-ov-file#use-the-filepickerbuilder ?

**Comment by Thatoo** [comment]
From which version of @nextcloud/dialogs is it possible to use `.addButton({})` with getFilePickerBuilder function?

**Comment by Thatoo** [comment]
It if from v 4.2.0 whereas Picker app is still using 3.1.2 which is the reason of this error.
Now I get a new error : 
```
FilePickerBuilder: When adding custom buttons the `type` must be set to `FilePickerType.Custom`.
```
I don't know what to do with it.

**Comment by susnux** [comment]
The FilePicker was added with version 4.2 so you need to use 4.2+ (or version 5 or later if you target Nextcloud 28+).

With versions before 4.2 you can only use some limited functions.


For your error:
> Failed to load the element <script> from « https://zyuno.local/apps/picker/js/picker-vendors-node_modules_path-browserify_index_js-node_modules_nextcloud_dialogs_dist_chunks_Dial-7445f9.js?v=8ddf27581abc54d78b9b ». NcButton-DhaPcomf.css:1

How do you bundle your app? This looks like you somehow include CSS imports in your final bundle which does not work for browsers but you have to either extract CSS to a file or inject inline (webpack or vite plugin).

**Comment by Thatoo** [comment]
Thank you @susnux for coming back to me.

I'm trying to improve this app : https://github.com/nextcloud/picker

Here is my work : https://github.com/Thatoo/picker/blob/ClipboardOnly/src/main.js

**Comment by Thatoo** [comment]
@susnux 
@nextcloud/dialogs 4.2 needs @nextcloud/vue right?
Does that imply other needs such as "vue" or "vue-material-design-icons" version?

**Comment by Thatoo** [comment]
If I add 
`import '@nextcloud/dialogs/style.css'`
below
`import { showError, getFilePickerBuilder } from '@nextcloud/dialogs'`
I get the following error when I try to build
`  10:8  error  Unable to resolve path to module '@nextcloud/dialogs/style.css'  import/no-unresolved`

**Comment by susnux** [comment]
> Does that imply other needs such as "vue" or "vue-material-design-icons" version?

Vue 2 is required then, others are dependencies and will be installed as needed.

>    10:8  error  Unable to resolve path to module '@nextcloud/dialogs/style.css'  import/no-unresolved

That plugin is simply broken, I think you can disable that ESLint plugin, the issue is open for a looong time:
https://github.com/import-js/eslint-plugin-import/issues/1810

**Comment by Thatoo** [comment]
Could you tell me how to disable  import/no-unresolved eslint plugin? In other word, how should I modify https://github.com/nextcloud/picker/blob/main/.eslintrc.js ?

**Comment by Thatoo** [comment]
I found it. I needed to add 
`"import/no-unresolved": "off"` to "rules" of .eslintrc.js

Now I have a prettier window thanks to css but it doesn't display files and I keep having the error in console listed earlier
```
[Vue warn]: Error in mounted hook (Promise/async): "TypeError: context is undefined"
...
[vue.runtime.esm.js:3049](webpack:///picker/node_modules/vue/dist/vue.runtime.esm.js)
[Vue warn]: Error in render: "RangeError: invalid array length"
...
```

**Comment by Thatoo** [comment]
I wonder, are nextcloud/dialogs v4.2 and nextcloud/vue v7.12 working on nextcloud v28?

**Comment by Thatoo** [comment]
I tried with the latest release @nextcloud/dialogs v 5.3.5 and @nextcloud/vue v 8.15.0, and it fully works!
Thank you @provokateurin for your help and patience.
