### ISSUE TITLE
Add confim()

### ISSUE THREAD

**Issue by thlehmann-ionos** [nextcloud-libraries/nextcloud-dialogs#1371]
## Background

* `OC.dialogs.confirm` is [to be deprecated in Nextcloud 30][1], but it's not yet included in the dialogs package
* `confirm()` was also [never declared in typings][2]

## Request 

`confirm()`
* to be added in one of the next releases
* to be declared as type in "typings"

## Workaround

Adding this as `src/oc.d.ts` to a typscript-able app:
```
/// <reference types="@nextcloud/typings" />

declare namespace Nextcloud28WithPolyfills {
	interface DialogsPolyfill {
		confirm(
	        title: string,
	        message: string,
	        callback: Function,
	        modal: boolean): void;
	}

    interface OC extends Nextcloud.v28.OC {
		dialogs: Nextcloud.Common.Dialogs & DialogsPolyfill;
    }
}

declare var OC: Nextcloud28WithPolyfills;
```

[1]: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html
[2]: https://github.com/nextcloud-libraries/nextcloud-typings/blob/v1.8.0/lib/common/OC.d.ts#L16

**Comment by susnux** [comment]
If you use Vue then I recommend simply directly using `NcDialog` from `@nextcloud/vue`.

If not you can use this library, as the replacement for the deprecated function is to use the `DialogBuilder` from this library, see:
https://nextcloud-libraries.github.io/nextcloud-dialogs/classes/index.DialogBuilder.html

**Comment by thlehmann-ionos** [comment]
Thanks for pointing that out.

Note: unfortunately, `<NcDialog>` leads to repetition and possibly inconsistent UI because every confirm dialog has to be re-implemented (icon, button order). ´. Same for the `DialogBuilder`, which is a bit better because it includes the facility for that, but still repeated code.
