### ISSUE TITLE
Include confirmDestructive Dialog

### ISSUE THREAD

**Issue by jotoeri** [nextcloud-libraries/nextcloud-dialogs#300]
Just wanted to use the confirmationDialog on Forms and saw i need to take it manually from `OC.dialogs`. Would imo be nice to have it included in this package!

**Comment by susnux** [comment]
This will not make it into 4.2.0 but I think about implementing the dialogs based on the new dialog component for 5.0.0, but we could also backport this for 4.3.0 to support this on Nextcloud 27 as well.
