### ISSUE TITLE
Make possible to specify the container for the filepicker dialog

### ISSUE THREAD

**Issue by danxuliu** [nextcloud-libraries/nextcloud-dialogs#427]
[The dialogs are appended to the body element](https://github.com/nextcloud/server/blob/3e624dc39966f54c6d418eee2e8141fc5c21f751/core/src/jquery/ocdialog.js#L55). However, in some cases the filepicker dialog needs to be appended to a different element (for example, [if a sub-element is shown in fullscreen mode](https://github.com/nextcloud/spreed/blob/0e56546895fb6f5eb366fb3636c8d9633f65409d/src/components/TopBar/TopBar.vue#L407-L419), like done in Talk), as otherwise it would not be visible.

This may require to adjust the `ocdialogs` function in server. Alternatively it might be possible to address this directly in _nextcloud-dialogs_ by [reparenting the dialog once it was created](https://github.com/nextcloud/nextcloud-dialogs/blob/892b19996f26a6d3d4cfff361ff89b76c952dbed/lib/filepicker.ts#L39), although I have not verified it.

Note that [the modal dialog overlay would also need to be reparented to the proper element](https://github.com/nextcloud/server/blob/3e624dc39966f54c6d418eee2e8141fc5c21f751/core/src/jquery/ocdialog.js#L219-L223).

## How to test

- Open a conversation in Talk
- Switch to full screen mode
- Try to share a file

### Expected result

The file picker dialog is shown.

### Actual result

The overlay is shown, but not the file picker dialog.

**Comment by ChristophWurst** [comment]
Easily done once we have https://github.com/nextcloud/nextcloud-dialogs/issues/1 :wink:

**Comment by susnux** [comment]
As we now have #1, I plan to implement this for 5.0.0 :)
