### ISSUE TITLE
Circular dependency with nextcloud/vue

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud-libraries/nextcloud-dialogs#885]
Now that the filepicker is implemented in Vue, we have a circular dependency between `nextcloud/dialogs` and `nextcloud/vue`. At the moment this is not a huge problem, but once we updated `nextcloud/dialogs` in `nextcloud/vue` to the latest release, and want to migrate to vue3, we won't be able to do it.

We had the same issue with `nextcloud/dashboard-vue`, and the solution was to merge dashboard into `nextcloud/vue`. I would propose to do the same here. What do you think @susnux @skjnldsv.

**Comment by susnux** [comment]
I do not think the Filepicker belongs to the nextcloud-vue library. It contains too much logic.
I am currently prepare the Dialog component to move to nextcloud-vue, as a generic NcDialog makes sense, while the FilePicker is build upon it but contains too much logic and will introduce other dependencies.

While circular dependencies are generally bad, I do not think it will be a problem here as we only use the dialogs package on one file for showing one error.
Maybe drop that reference or create a new entry point for `@nextcloud/dialogs/toasts`. The toasts do not depend on Vue so there will no circular dependency.

**Comment by raimund-schluessler** [comment]
> I do not think the Filepicker belongs to the nextcloud-vue library. It contains too much logic.

I understand what you mean. I also don't think it would fit ideally, but one way or the other, we need to resolve this circular dependency.

> While circular dependencies are generally bad, I do not think it will be a problem here as we only use the dialogs package on one file for showing one error. Maybe drop that reference or create a new entry point for `@nextcloud/dialogs/toasts`. The toasts do not depend on Vue so there will no circular dependency.

It might not be an issue in the daily operation. But once we attempt to update to vue 3, we won't e able to. Even if the part we use from nextcloud/dialogs in nextcloud/vue doesn't even depend on vue, npm will try to install vue with it and require a conflicting dependency. And we won't be able to upgrade either package, as it is missing a vue 3 compatible version of the other. And then boom.

Maybe on other solution would be to split nextcloud/dialogs into one package required by nextcloud/vue, without dependency to vue, and a second package containing the filepicker and vue dependencies.

**Comment by skjnldsv** [comment]
> Now that the filepicker is implemented in Vue, we have a circular dependency between `nextcloud/dialogs` and `nextcloud/vue`. At the moment this is not a huge problem, but once we updated `nextcloud/dialogs` in `nextcloud/vue` to the latest release, and want to migrate to vue3, we won't be able to do it.

Why wouldn't you be able to specify different versions ?
You can upgrade to vue3 and still use @nc/dialogs (vue2) in @nc/vue, no?
Once @nc/dialogs is upgraded to vue 3 , we'll also update it?

They're not bound with master branches, we can always pin the versions until one upgrade is compatible?

**Comment by raimund-schluessler** [comment]
> Why wouldn't you be able to specify different versions ? You can upgrade to vue3 and still use @nc/dialogs (vue2) in @nc/vue, no? Once @nc/dialogs is upgraded to vue 3 , we'll also update it?
> 
> They're not bound with master branches, we can always pin the versions until one upgrade is compatible?

I don't know whether one can get it to work like this. I can only tell you, that what I tried gave me a conflicting peer dependency error by npm. I tried to upgrade `nextcloud/dialogs` to `4.2.0-beta.2` in the `nextcloud/vue` `vue3` branch and got this error:
<pre><span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> <span style="color:#A347BA">code</span> ERESOLVE
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> <span style="color:#A347BA">ERESOLVE</span> unable to resolve dependency tree
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> 
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> While resolving: <b>@nextcloud/vue</b>@<b>8.0.0-beta.2</b>
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> Found: <b>vue</b>@<b>3.3.4</b>
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> node_modules/vue
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span>   <b>vue</b>@&quot;<b>^3.3.4</b>&quot; from the root project
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> 
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> Could not resolve dependency:
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> <span style="color:#A347BA">peer</span> <b>vue</b>@&quot;<b>^2.7.14</b>&quot; from <b>@nextcloud/dialogs</b>@<b>4.2.0-beta.2</b>
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> node_modules/@nextcloud/dialogs
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span>   <b>@nextcloud/dialogs</b>@&quot;<b>^4.2.0-beta.2</b>&quot; from the root project
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> 
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> Fix the upstream dependency conflict, or retry
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> this command with --force or --legacy-peer-deps
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> to accept an incorrect (and potentially broken) dependency resolution.
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> 
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> 
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> For a full report see:
<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> /home/raimund/.npm/_logs/2023-08-12T10_55_54_003Z-eresolve-report.txt

<span style="background-color:#171421"><span style="color:#D0CFCC">npm</span></span> <span style="background-color:#171421"><span style="color:#C01C28">ERR!</span></span> A complete log of this run can be found in: /home/raimund/.npm/_logs/2023-08-12T10_55_54_003Z-debug-0.log</pre>

**Comment by skjnldsv** [comment]
Right, because we're not bundling `nextcloud/vue` inside `nextcloud/dialogs`
If we do, then we can drop the peer dependency and we should be good.



> One option would be to keep `nextcloud/dialogs` at `4.1.0` (which has no vue dependency at all) in `nextcloud/vue#vue3`, do a `nextcloud/vue#vue3` release, migrate `nextcloud/dialogs` to vue3, release it, update `nextcloud/vue` to `nextcloud/dialogs#vue3` and release again.

That's what I had in mind yep :)

**Comment by skjnldsv** [comment]
> a component library without logic

Can you elaborate? :)
