### ISSUE TITLE
Question: Should the file picker have a fixed size?

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-dialogs#900]
Currently the file picker is not fixed in height, it is just clamped to a minimum of 4 file entries (so the skeleton entries do not cause jumping when the actual loaded content has less than 4 entries).

But if the actual listing has more than 4 entries the file picker size is "jumping". 
So to prevent this we must set a fixed height to the file picker, we could e.g. set it to 90vh¹.

cc @szaimen @jancborchardt @nimishavijay

¹ Not required for mobile as it is always full screen there.

**Comment by szaimen** [comment]
> So to prevent this we must set a fixed height to the file picker, we could e.g. set it to 90vh¹.

yes, lets do this 👍

**Comment by jancborchardt** [comment]
Yes it should have a fixed height, it shouldn't jump. :) 90 or 80vh seem good, has to be compared in practice.

**Comment by jancborchardt** [comment]
And @susnux @szaimen it would be good to have that for 27.1 since the jumping is quite noticeable. (So I assume to be merged until tomorrow.)

**Comment by susnux** [comment]
> as said it would be good to have that for 27.1 since the jumping is quite noticeable. (So I assume to be merged until tomorrow.)

If I understood it correctly we can still fix this for beta 3 next week. This way we can also fix any issue we might discover on the design review Tuesday.

**Comment by szaimen** [comment]
I guess the peoblem would be how it would look like e.g. with 90vh if there is only a small filelist?
