### ISSUE TITLE
file picker should show hidden folders

### ISSUE THREAD

**Issue by j-lakeman** [nextcloud-libraries/nextcloud-dialogs#908]
Title should be explanatory enough.
Please see https://github.com/nextcloud/bookmarks/issues/2046

**Comment by susnux** [comment]
The new Vue based file picker (Nextcloud 27.1 and Nextcloud 28+) does not hide those files currently so this is "fixed".

But this is a good catch, @nimishavijay should we hide hidden files and how would a user show them?
Should we offer a own setting to show hidden files, like OS file pickers do, or should we use the settings of the files app?

**Comment by j-lakeman** [comment]
Great!
Can't wait to update my server!

**Comment by nimishavijay** [comment]
> should we use the settings of the files app?

This sounds like a good solution to me. It's most likely that the only people who would choose something from a hidden folder in the file picker are the people who use the file picker regularly and have it visible in Files. So whatever is set in the Files settings can be reflected in the file picker also :)
