### ISSUE TITLE
Return string when multiSelect is false

### ISSUE THREAD

**Issue by Pytal** [nextcloud-libraries/nextcloud-dialogs#919]
The return value for `pick()` is always an array of strings https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/42a3613523ea6625f51b485c38de7c3b29f1f021/lib/filepicker.ts#L72

When `multiSelect` is false it should just be a string

**Comment by Pytal** [comment]
What do you think @susnux?

**Comment by susnux** [comment]
This was the way it worked before version 5 :sweat_smile: 
But if you think this would make the usage easier, then lets revert this change. Better a bit more work in the library then everytime you use it.

**Comment by Pytal** [comment]
Or was there any reason to change the behaviour from before as it was already intuitive

Otherwise yes, let's revert :)
