### ISSUE TITLE
Drop `MimeType.getIconUrl`

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud-libraries/nextcloud-dialogs#943]
On 28, we'll deprecate that front API and sugges to use the preView controller new redirect to mime instead

Refs: 
- https://github.com/nextcloud/server/commit/28725c46a84db6e733c42e38cbc5e1b7f0e3854b
- https://github.com/nextcloud/server/blob/28725c46a84db6e733c42e38cbc5e1b7f0e3854b/core/Controller/PreviewController.php#L154
- https://github.com/nextcloud/server/blob/28725c46a84db6e733c42e38cbc5e1b7f0e3854b/apps/files/src/components/FileEntry.vue#L380-L399

**Comment by susnux** [comment]
Do you think it makes sense to provide the URL with the files library?
either some `getPreviewURL(node: Node)` function or as a method of the `Node` class?

**Comment by susnux** [comment]
Or is there some documentation of this API?
