### ISSUE TITLE
Throw when cancelling or clicking outside

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud-libraries/nextcloud-dialogs#946]
When you click outside or close, it still returns a path: `"/"`.

Example given: For the Move action, if you click outside, I expect to cancel.
Right now it's impossible to differentiate a cancellation and picking the root folder

**Comment by susnux** [comment]
What API?
* The FilePickerBuilder rejects the returned promise on close / cancel.
* The Vue commponent emits the `close` event

At least that is what should happen, if it does not, than this is a bug.

**Comment by skjnldsv** [comment]
`picker.pick()` should throw?
I'm not seeing this unfortunately :/

See https://github.com/nextcloud/server/blob/6c632a17c5912c330b045b6f1d85025a9d9d9f7b/apps/files/src/actions/moveOrCopyAction.ts#L200-L203, what am I doing wrong?

**Comment by susnux** [comment]
> picker.pick() should throw?

Yes it should reject:

https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/b6ad9c011ed1b52957726241cd76808775b57db4/lib/filepicker.ts#L87

**Comment by skjnldsv** [comment]
It doesn't :see_no_evil:

**Comment by susnux** [comment]
Well then this is a bug, I try to investigate
