### ISSUE TITLE
Add patch-package to dependencies

### ISSUE THREAD

**Issue by Pytal** [nextcloud-libraries/nextcloud-dialogs#983]
When updating to v4.2.0 beta.5 https://github.com/nextcloud/server/pull/40281 an error will be thrown saying that `patch-package` is not found

https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/v4.2.0-beta.5/package.json#L81 should be moved to dependencies

**Comment by susnux** [comment]
Can be dropped now the fix is merged upstream and released, we just need to depend on the new webdav package release.
